language: python

python:
  - '3.4'
  - '2.7'

os:
  - linux
  - windows

install:
  - pip install coveralls
  - pip install nltk
  - pip install -r requirements.txt

services:
  - mongodb

script:
  - nosetests  --with-coverage --cover-package=chatterbot

after_success:
  - coveralls
