# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.md

# command to run tests
script: nosetests

after_success:
    coveralls
